<template>
  <div id="dashboard">
    <h1>That's the dashboard!</h1>
    <p>You should only get here if you're authenticated!</p>
    <p>Your email address is {{ email }}</p>
  </div>
</template>

<script>
// We import axios in main.js and set global defaults. We still need to import axios in each
// component we use. The axios import will be merged, so the defaults are set through main.js
import axios from 'axios'

export default {
  data () {
    return {
      email: ''
    }
  },
  created () {
    axios.get('/users.json')
      .then(response => {
        console.log(response)
        // The data return by axios is an object not an array with a key generated by firebase
        // we need to loop through the response.data with a 'for in' loop and push each element to a new array (users)
        // 'for in' loop returns the key. To return values you need 'for of' loop
        const users = []
        const data = response.data
        for (let key in data) {
          // key will hold the generated firebase key of the data record
          // setting user = data[key] sets the user with all the object data
          const user = data[key]
          // we add id as new property to the user object to hold the key
          user.id = key
          // we push the user object to the users array
          users.push(user)
        }
        console.log(users)
        // set the email from the first user in the users array
        this.email = users[0].email
      })
      .catch(error => {
        console.log(error)
      })
  }
}
</script>


<style scoped>
  h1, p {
    text-align: center;
  }

  p {
    color: red;
  }
</style>